spring.application.name=keychain-wallet

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/keychain}
spring.datasource.username=${DB_USER:keychain}
spring.datasource.password=${DB_PASS:keychain}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=${PORT:8080}
